### ISSUE TITLE
Array mutating problem when calculating inverse of (I + M)

### ISSUE THREAD

**Issue by MrstupidJ** [acfr/RobustNeuralNetworks.jl#139]
https://github.com/acfr/RobustNeuralNetworks.jl/blob/67f9f813649473cf311a8c7960c540a3df668ac9/src/ParameterTypes/passive_ren.jl#L115

There is an array mutating in $\rho \neq 0$ case. This will not affect constructing a model with the corresponding robust property, however, this will affect learning/training of the model via Zygote. 

Shall be fixed ASAP.

**Comment by MrstupidJ** [comment]
The problem is likely introduced when we calculate D22 [(this line)](https://github.com/acfr/RobustNeuralNetworks.jl/blob/67f9f813649473cf311a8c7960c540a3df668ac9/src/ParameterTypes/passive_ren.jl#L117C1-L117C31) . 

Not sure about the fix yet, but we could use general paramterisation for now.

**Comment by nic-barbara** [comment]
@MrstupidJ we use the following function to calculate D22:
```julia
_D22_pass(M, ρ) = ((I+M) \ I) / ρ
```
As far as I'm aware that shouldn't be mutating any arrays.

Could you please provide a minimal example reproducing the error to help with debugging?

**Comment by MrstupidJ** [comment]
Applied the same fix as [here](https://github.com/acfr/RobustNeuralNetworks.jl/blob/67f9f813649473cf311a8c7960c540a3df668ac9/src/ParameterTypes/general_ren.jl#L153).
