### ISSUE TITLE
Mixing convolutions with LBDN

### ISSUE THREAD

**Issue by pat-alt** [acfr/RobustNeuralNetworks.jl#149]
This is a very naive question @nic-barbara, but since you're working in the field you'll probably be able to give me a quick answer. 

I'm working on an image classification problem and intend to not only use Lipschitz bounded dense layers, but also convolutions. To give you a specific example, say we have LeNet-type network as follows,

```julia
julia> model
Chain(
  ARME.ToConv(28),
  Chain(
    Conv((5, 5), 1 => 6, relu, pad=2),  # 156 parameters
    MaxPool((2, 2)),
    Conv((5, 5), 6 => 16, relu, pad=2),  # 2_416 parameters
    MaxPool((2, 2)),
    Flux.flatten,
  ),
  DiffLBDN(
    DenseLBDNParams(
      RobustNeuralNetworks.DirectLBDNParams{Float32, 3, 2}((Float32[-0.07281888 -0.023452861 … 0.02258001 -0.017421778; -0.008015712 -0.012554392 … 0.04726529 0.015373676; … ; 0.028101666 0.06337687 … 0.05126092 -0.01614618; -0.013814994 0.05993527 … 0.03461697 0.009724649], Float32[0.0477182 -0.026614765 … -0.07668863 -0.08407785; -0.0050611864 0.13845734 … 0.05637419 -0.06558655; … ; 0.17586067 0.005029241 … 0.018579142 0.14699522; 0.015149078 -0.08210437 … 0.0935068 0.008000422], Float32[0.052503712 -0.04530235 … 0.10250387 0.2529985; -0.07309061 0.0129929995 … -0.0580655 0.08636158; … ; -0.053290997 0.054476775 … 0.15038617 -0.1491381; -0.062418956 -0.109666325 … 0.11627818 0.0021336987]), (Float32[14.567893], Float32[12.654198], Float32[4.225466]), (Float32[-0.1446041, -0.058322005, 0.18543763, 0.30695286, 0.29139647, -0.047599863, 0.2335458, 0.020663623, -0.19120818, -0.059376333  …  0.11467696, -0.09578089, 0.1618799, -0.07838926, -0.01914913, 0.06640194, -0.1830713, -0.13185368, 0.07386127, -0.08486061], Float32[0.16591375, 0.13720408, 0.0040792925, -0.042155433, 0.09516066, 0.037793953, -0.2605028, -0.008944715, -0.13061137, -0.039210584  …  0.09081496, -0.12515077, -0.27820998, -0.06798387, -0.13280517, -0.022483828, -0.12823363, 0.12747557, -0.11259732, 0.0046946174]), (Float32[-0.06581022, 0.21328256, 0.09024873, -0.0017572856, 0.038347572, -0.23335123, 0.039512254, 0.19888169, 0.024689823, 0.107272044  …  0.039018072, -0.018863695, 0.03368117, -0.011614998, 0.05097574, -0.07531259, -0.05187632, -0.05213088, 0.022005893, -0.0031537048], Float32[-0.00012706411, 0.021876961, -0.15178928, -0.07904826, 0.07538053, -0.085640386, 0.17980106, 0.19084911, 0.16415401, 0.0013714323  …  -0.29879108, 0.049220815, -0.15795642, -0.11716579, 0.07489176, 0.16065657, 0.1692633, -0.26709902, -0.03450471, -0.22906299], Float32[0.5048571, -0.3563841, -0.3664207, -0.41608804, -0.2902878, 0.004180035, -0.6404611, 0.13514931, -0.27184883, 0.7278865]), Float32[0.0], false),  # 139_073 parameters, plus 1
    ),
  ),
)         # Total: 15 trainable arrays, 141_645 parameters,
          # plus 1 non-trainable, 1 parameters, summarysize 555.422 KiB.
```

where the backbone is a ConvNet and the header is an LBDN.

I've tried training this and it works, but I'm wondering what the theoretical implications are. Is this a viable approach? More specifically, can I still argue that this should improve robustness compared to a conventional network?

Thanks in advance!

PS: I saw your talk at JCon 2023 and I'm finally coming back to this - really cool stuff!

**Comment by nic-barbara** [comment]
Hey @pat-alt, great question! Thanks for reaching out.

Yep you can definitely argue that Lipschitz bounding the output should improve robustness compared to a conventional network. However, you could still see pretty sensitive behaviour from the convolutional layers that may harm performance.

A better way is to use convolutional LBDN layers too. I did this recently in [this paper](https://arxiv.org/abs/2405.11432) and found that it can considerably improve robustness in RL tasks.

I don't currently have an implementation of convolutional LBDNs in this package, but I do have a PyTorch implementation [here](https://github.com/nic-barbara/Lipschitz-RL-Atari/blob/main/liprl/networks/lbdn.py#L91). It shouldn't be too hard to write a Julia version (and if you have the time to add this to `RobustNeuralNetworks.jl` feel free to submit a PR)

Let me know if you have further questions, happy to help!

**Comment by pat-alt** [comment]
Hi @nic-barbara! Thanks for the quick response and great to hear. I'll have a look at your PyTorch implementation as well. Thanks!
