### ISSUE TITLE
Use Flux.Recur to run nonlinear simulation

### ISSUE THREAD

**Issue by MrstupidJ** [acfr/RobustNeuralNetworks.jl#67]
https://github.com/acfr/RobustNeuralNetworks.jl/blob/b7b1bee1dba0d5273e9bd1ae2ebe73f59e04f184/examples/src/lbdn_rl.jl#L48

@raywang1987 I copied this piece of code (for running nonlinear system simulation) from our previous example (or maybe we did not use this, as the old example was linear), but it seems not working now.

**Comment by nic-barbara** [comment]
This might be fixed by proper use of `@functor` from https://github.com/acfr/RobustNeuralNetworks.jl/issues/105#issuecomment-1666225961.

**Comment by MrstupidJ** [comment]
The Flux document on [Flux.Recur](http://fluxml.ai/Flux.jl/stable/models/layers/#Flux.Recur) was a bit confusing to control people. A simple example provided by the document was using an accumulation function as the cell: 
`accum(h, x) = (h + x, x)`
`rnn = Flux.Recur(accum, 0)` 
In Flux doc, `h` is the hidden states, `x` is the input to the cell. 

To use `Flux.Recur` in control context, one can define a (discrete-time) nonlinear system dynamic as:
`x, y = f(x, u)`
(Note: the order of returned value matters, Flux will take the first as hidden states and second as output)
Then it can be initialized as a Flux model with initial state _x0_
`model =  Flux.Recur(f, x0)`
Simulate one time step given input _u(t)_: 
`y = model(u(t))`
The hidden state (sate of the dynamic system) can be accessed in `model.state`.
